name: trans

env:
  RELEASE: ${{ github.ref }}

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set ENV
        run: |
          echo "Name: ${{ github.event.release.name }} Description: ${{ github.event.release.body }}"
          echo "FROM_IMAGE=${RELEASE#refs/tags/}" >> $GITHUB_ENV
          echo "TO_IMAGE=`echo $FROM_IMAGE|sed 's/\//_/g'`" >> $GITHUB_ENV
      
      - name: Build and push
        id: docker_build
        run: | 
          docker pull ${FROM_IMAGE}
          docker tag ${FROM_IMAGE} ${TO_IMAGE}
          docker push ${TO_IMAGE}
